apiVersion: v1
kind: Secret
metadata:
  name: sc-mlops-secrets
  namespace: sc-mlops
type: Opaque
stringData:
  JWT_SECRET_KEY: "change_me_in_production"
  API_KEY: "change_me_in_production"
  MLFLOW_TRACKING_URI: "https://dagshub.com/Liora-Team/supply-chain-ml-ops.mlflow"
  MLFLOW_TRACKING_USERNAME: "replace_with_username"
  MLFLOW_TRACKING_PASSWORD: "replace_with_token"
  